Add Esperanto translation (need to test in-game)
alemart/opensurge pull request #57
Opened 2021-10-29 16:08 UTC by jorgesumle

2021-11-02 03:25 UTC, alemart requested changes
Some strings related to the level editor are missing. Still waiting for your response (see my previous comment).

2021-11-02 08:37 UTC, jorgesumle commented
Sorry, I wanted to reply when I finish the translation, but I haven't yet. Yes, I can update the translation from time to time, but please notify me via email or something when new strings are added.

2021-11-02 23:58 UTC, jorgesumle commented
I tried to compile the game to test the translation in-game, but I got the following error:

```
$ make
Scanning dependencies of target opensurge
[  0%] Building C object CMakeFiles/opensurge.dir/src/core/nanoparser/nanoparser.c.o
[  1%] Building C object CMakeFiles/opensurge.dir/src/core/whereami/whereami.c.o
[  2%] Building C object CMakeFiles/opensurge.dir/src/core/utf8/utf8.c.o
[  3%] Building C object CMakeFiles/opensurge.dir/src/core/zip/zip.c.o
[  4%] Building C object CMakeFiles/opensurge.dir/src/core/assetfs.c.o
[  5%] Building C object CMakeFiles/opensurge.dir/src/core/audio.c.o
[  6%] Building C object CMakeFiles/opensurge.dir/src/core/color.c.o
[  7%] Building C object CMakeFiles/opensurge.dir/src/core/commandline.c.o
[  8%] Building C object CMakeFiles/opensurge.dir/src/core/csv.c.o
[  9%] Building C object CMakeFiles/opensurge.dir/src/core/engine.c.o
[ 10%] Building C object CMakeFiles/opensurge.dir/src/core/font.c.o
[ 11%] Building C object CMakeFiles/opensurge.dir/src/core/fontext.c.o
[ 12%] Building C object CMakeFiles/opensurge.dir/src/core/image.c.o
[ 13%] Building C object CMakeFiles/opensurge.dir/src/core/input.c.o
[ 14%] Building C object CMakeFiles/opensurge.dir/src/core/inputmap.c.o
[ 15%] Building C object CMakeFiles/opensurge.dir/src/core/install.c.o
[ 16%] Building C object CMakeFiles/opensurge.dir/src/core/lang.c.o
[ 17%] Building C object CMakeFiles/opensurge.dir/src/core/logfile.c.o
[ 18%] Building C object CMakeFiles/opensurge.dir/src/core/modmanager.c.o
[ 19%] Building C object CMakeFiles/opensurge.dir/src/core/web.c.o
[ 20%] Building C object CMakeFiles/opensurge.dir/src/core/prefs.c.o
[ 21%] Building C object CMakeFiles/opensurge.dir/src/core/quest.c.o
[ 22%] Building C object CMakeFiles/opensurge.dir/src/core/resourcemanager.c.o
[ 23%] Building C object CMakeFiles/opensurge.dir/src/core/scene.c.o
[ 24%] Building C object CMakeFiles/opensurge.dir/src/core/screenshot.c.o
[ 25%] Building C object CMakeFiles/opensurge.dir/src/core/fadefx.c.o
[ 25%] Building C object CMakeFiles/opensurge.dir/src/core/sprite.c.o
[ 26%] Building C object CMakeFiles/opensurge.dir/src/core/storyboard.c.o
[ 27%] Building C object CMakeFiles/opensurge.dir/src/core/stringutil.c.o
[ 28%] Building C object CMakeFiles/opensurge.dir/src/core/timer.c.o
[ 29%] Building C object CMakeFiles/opensurge.dir/src/core/util.c.o
[ 30%] Building C object CMakeFiles/opensurge.dir/src/core/v2d.c.o
[ 31%] Building C object CMakeFiles/opensurge.dir/src/core/video.c.o
[ 32%] Building C object CMakeFiles/opensurge.dir/src/scenes/util/editorcmd.c.o
[ 33%] Building C object CMakeFiles/opensurge.dir/src/scenes/util/editorgrp.c.o
[ 34%] Building C object CMakeFiles/opensurge.dir/src/scenes/util/grouptree.c.o
[ 35%] Building C object CMakeFiles/opensurge.dir/src/scenes/confirmbox.c.o
[ 36%] Building C object CMakeFiles/opensurge.dir/src/scenes/credits.c.o
[ 37%] Building C object CMakeFiles/opensurge.dir/src/scenes/editorhelp.c.o
[ 38%] Building C object CMakeFiles/opensurge.dir/src/scenes/editorpal.c.o
[ 39%] Building C object CMakeFiles/opensurge.dir/src/scenes/gameover.c.o
[ 40%] Building C object CMakeFiles/opensurge.dir/src/scenes/intro.c.o
[ 41%] Building C object CMakeFiles/opensurge.dir/src/scenes/langselect.c.o
[ 42%] Building C object CMakeFiles/opensurge.dir/src/scenes/level.c.o
[ 43%] Building C object CMakeFiles/opensurge.dir/src/scenes/options.c.o
[ 44%] Building C object CMakeFiles/opensurge.dir/src/scenes/pause.c.o
[ 45%] Building C object CMakeFiles/opensurge.dir/src/scenes/quest.c.o
[ 46%] Building C object CMakeFiles/opensurge.dir/src/scenes/questselect.c.o
[ 47%] Building C object CMakeFiles/opensurge.dir/src/scenes/stageselect.c.o
[ 48%] Building C object CMakeFiles/opensurge.dir/src/scripting/scripting.c.o
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c: In function ‘scripting_util_world_position’:
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:227:5: warning: implicit declaration of function ‘surgescript_transform_util_worldposition2d’; did you mean ‘surgescript_transform_setposition2d’? [-Wimplicit-function-declaration]
  227 |     surgescript_transform_util_worldposition2d(object, &position.x, &position.y);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     surgescript_transform_setposition2d
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c: In function ‘scripting_util_world_angle’:
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:234:12: warning: implicit declaration of function ‘surgescript_transform_util_worldangle2d’; did you mean ‘surgescript_transform_translate2d’? [-Wimplicit-function-declaration]
  234 |     return surgescript_transform_util_worldangle2d(object);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            surgescript_transform_translate2d
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c: In function ‘scripting_util_set_world_position’:
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:240:5: warning: implicit declaration of function ‘surgescript_transform_util_setworldposition2d’; did you mean ‘surgescript_transform_setposition2d’? [-Wimplicit-function-declaration]
  240 |     surgescript_transform_util_setworldposition2d(object, position.x, position.y);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     surgescript_transform_setposition2d
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c: In function ‘scripting_util_set_world_angle’:
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:246:5: warning: implicit declaration of function ‘surgescript_transform_util_setworldangle2d’; did you mean ‘surgescript_transform_setscale2d’? [-Wimplicit-function-declaration]
  246 |     surgescript_transform_util_setworldangle2d(object, angle);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     surgescript_transform_setscale2d
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c: In function ‘setup_surgeengine’:
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:397:5: warning: implicit declaration of function ‘surgescript_transform_use_inverted_y’; did you mean ‘surgescript_transform_apply2dinverse’? [-Wimplicit-function-declaration]
  397 |     surgescript_transform_use_inverted_y(true);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     surgescript_transform_apply2dinverse
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c: In function ‘compile_script’:
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:447:5: error: unknown type name ‘surgescript_parser_t’; use ‘struct’ keyword to refer to the type
  447 |     surgescript_parser_t* parser = (surgescript_parser_t*)param;
      |     ^~~~~~~~~~~~~~~~~~~~
      |     struct 
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:447:37: error: ‘surgescript_parser_t’ undeclared (first use in this function)
  447 |     surgescript_parser_t* parser = (surgescript_parser_t*)param;
      |                                     ^~~~~~~~~~~~~~~~~~~~
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:447:37: note: each undeclared identifier is reported only once for each function it appears in
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:447:58: error: expected expression before ‘)’ token
  447 |     surgescript_parser_t* parser = (surgescript_parser_t*)param;
      |                                                          ^
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:448:5: error: unknown type name ‘surgescript_parser_flags_t’; did you mean ‘surgescript_program_t’?
  448 |     surgescript_parser_flags_t flags = SSPARSER_DEFAULTS;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |     surgescript_program_t
/home/jorge/Repositorios/opensurge/src/scripting/scripting.c:448:40: error: ‘SSPARSER_DEFAULTS’ undeclared (first use in this function)
  448 |     surgescript_parser_flags_t flags = SSPARSER_DEFAULTS;
      |                               [...]

2021-11-03 12:45 UTC, alemart commented
Hi @jorgesumle . Thank you for your update.

> I tried to compile the game to test the translation in-game, but I got the following error:

You need to install [libsurgescript](https://github.com/alemart/surgescript) before you can compile Open Surge. Please try again and let me know what happens.

> Yes, I can update the translation from time to time, but please notify me via email or something when new strings are added.

I'll be using the email address you have included in the translation file, ok?

2021-11-03 17:10 UTC, jorgesumle commented
```
18:08 $ apt show surgescript 
Package: surgescript
Version: 0.5.4-1
Priority: optional
Section: universe/graphics
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1.465 kB
Depends: libc6 (>= 2.29)
Homepage: https://docs.opensurge2d.org
Download-Size: 358 kB
APT-Manual-Installed: yes
APT-Sources: http://es.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: Scripting language for games
 Unleash your creativity! With SurgeScript, you unleash your creativity
 and create your own amazing interactive content.
 .
 Unlike other programming languages, SurgeScript is designed with the specific
 needs of games in mind.
 .
 Easy for beginners, powerful for experts. Object-oriented, dynamically typed
 and based on state machines.
 .
 These features come from the experience of the developer dealing with
 game engines, applications related to computer graphics and so on.
 .
 Some of the best practices have been incorporated into the language itself,
 making things really easy for developers and modders.

✔ ~/Repositorios/opensurge/build [master ↑·3|✔] 
18:08 $ opensurge --version
0.5.2.1
18:09 $ cmake ..
Open Surge version 0.6.0.0
-- Building using the Allegro 5 backend...
-- Found liballegro at /usr/lib/x86_64-linux-gnu/liballegro.so...
-- Found liballegro_image at /usr/lib/x86_64-linux-gnu/liballegro_image.so...
-- Found liballegro_primitives at /usr/lib/x86_64-linux-gnu/liballegro_primitives.so...
-- Found liballegro_font at /usr/lib/x86_64-linux-gnu/liballegro_font.so...
-- Found liballegro_ttf at /usr/lib/x86_64-linux-gnu/liballegro_ttf.so...
-- Found liballegro_acodec at /usr/lib/x86_64-linux-gnu/liballegro_acodec.so...
-- Found liballegro_audio at /usr/lib/x86_64-linux-gnu/liballegro_audio.so...
-- Found liballegro_dialog at /usr/lib/x86_64-linux-gnu/liballegro_dialog.so...
-- Found liballegro_memfile at /usr/lib/x86_64-linux-gnu/liballegro_memfile.so...
-- Found libsurgescript at /usr/lib/libsurgescript.a...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jorge/Repositorios/opensurge/build
✔ ~/Repositorios/opensurge/build [master ↑·3|✔] 
18:09 $ sudo make
[  1%] Building C object CMakeFiles/opensurge.dir/src/scripting/scripting.c.o
In file included from /home/jorge/Repositorios/opensurge/src/scripting/../entities/brick.h:25,
                 from /home/jorge/Repositorios/opensurge/src/scripting/scripting.h:26,
                 from /home/jorge/Repositorios/opensurge/src/scripting/scripting.c:22:
/home/jorge/Repositorios/opensurge/src/scripting/../entities/../core/color.h:29:10: fatal error: allegro5/allegro.h: Ficheiro ou pasta inexistente
   29 | #include <allegro5/allegro.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/opensurge.dir/build.make:700: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o] Erro 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/opensurge.dir/all] Erro 2
make: *** [Makefile:130: all] Erro 2
```

2021-11-03 17:15 UTC, jorgesumle commented
I also compiled libsurgescript from source, but I got the same error:

```
18:12 $ surgescript -v
0.5.5.1
✔ ~/Repositorios/opensurge/build [master ↑·3|✔] 
18:12 $ make 
[  1%] Building C object CMakeFiles/opensurge.dir/src/scripting/scripting.c.o
In file included from /home/jorge/Repositorios/opensurge/src/scripting/../entities/brick.h:25,
                 from /home/jorge/Repositorios/opensurge/src/scripting/scripting.h:26,
                 from /home/jorge/Repositorios/opensurge/src/scripting/scripting.c:22:
/home/jorge/Repositorios/opensurge/src/scripting/../entities/../core/color.h:29:10: fatal error: allegro5/allegro.h: Ficheiro ou pasta inexistente
   29 | #include <allegro5/allegro.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/opensurge.dir/build.make:700: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o] Erro 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/opensurge.dir/all] Erro 2
make: *** [Makefile:130: all] Erro 2
```

2021-11-04 15:31 UTC, alemart commented
Okay @jorgesumle , now you need the Allegro 5 header files. Please run the command below and try again.
```
sudo apt install liballegro5-dev liballegro-audio5-dev liballegro-dialog5-dev liballegro-image5-dev liballegro-ttf5-dev
```
Let me know how it goes.

2021-11-08 11:35 UTC, alemart requested changes
Waiting for your reply.

2021-11-08 13:43 UTC, jorgesumle commented
```
14:42 $ sudo make
[  1%] Building C object CMakeFiles/opensurge.dir/src/scripting/scripting.c.o
[  2%] Building C object CMakeFiles/opensurge.dir/src/scripting/application.c.o
[  3%] Building C object CMakeFiles/opensurge.dir/src/scripting/surgeengine.c.o
[  3%] Building C object CMakeFiles/opensurge.dir/src/scripting/actor.c.o
[  4%] Building C object CMakeFiles/opensurge.dir/src/scripting/animation.c.o
[  5%] Building C object CMakeFiles/opensurge.dir/src/scripting/brick.c.o
[  6%] Building C object CMakeFiles/opensurge.dir/src/scripting/camera.c.o
[  7%] Building C object CMakeFiles/opensurge.dir/src/scripting/collisions.c.o
[  8%] Building C object CMakeFiles/opensurge.dir/src/scripting/console.c.o
[  9%] Building C object CMakeFiles/opensurge.dir/src/scripting/events.c.o
[ 10%] Building C object CMakeFiles/opensurge.dir/src/scripting/input.c.o
[ 11%] Building C object CMakeFiles/opensurge.dir/src/scripting/lang.c.o
[ 12%] Building C object CMakeFiles/opensurge.dir/src/scripting/level.c.o
[ 13%] Building C object CMakeFiles/opensurge.dir/src/scripting/levelmanager.c.o
[ 14%] Building C object CMakeFiles/opensurge.dir/src/scripting/mouse.c.o
[ 15%] Building C object CMakeFiles/opensurge.dir/src/scripting/music.c.o
[ 16%] Building C object CMakeFiles/opensurge.dir/src/scripting/obstaclemap.c.o
[ 17%] Building C object CMakeFiles/opensurge.dir/src/scripting/player.c.o
[ 18%] Building C object CMakeFiles/opensurge.dir/src/scripting/prefs.c.o
[ 19%] Building C object CMakeFiles/opensurge.dir/src/scripting/screen.c.o
[ 20%] Building C object CMakeFiles/opensurge.dir/src/scripting/sensor.c.o
[ 21%] Building C object CMakeFiles/opensurge.dir/src/scripting/sound.c.o
[ 22%] Building C object CMakeFiles/opensurge.dir/src/scripting/text.c.o
[ 23%] Building C object CMakeFiles/opensurge.dir/src/scripting/time.c.o
[ 24%] Building C object CMakeFiles/opensurge.dir/src/scripting/transform.c.o
[ 25%] Building C object CMakeFiles/opensurge.dir/src/scripting/vector2.c.o
[ 26%] Building C object CMakeFiles/opensurge.dir/src/scripting/web.c.o
[ 27%] Building C object CMakeFiles/opensurge.dir/src/physics/obstacle.c.o
[ 28%] Building C object CMakeFiles/opensurge.dir/src/physics/obstaclemap.c.o
[ 28%] Building C object CMakeFiles/opensurge.dir/src/physics/physicsactor.c.o
[ 29%] Building C object CMakeFiles/opensurge.dir/src/physics/sensor.c.o
[ 30%] Building C object CMakeFiles/opensurge.dir/src/physics/sensorstate.c.o
[ 31%] Building C object CMakeFiles/opensurge.dir/src/physics/collisionmask.c.o
[ 32%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/item.c.o
[ 33%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/enemy.c.o
[ 34%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/object_compiler.c.o
[ 35%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/object_decorators.c.o
[ 36%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/object_machine.c.o
[ 37%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/object_vm.c.o
[ 38%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/nanocalc/nanocalc.c.o
[ 39%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/nanocalc/nanocalc_addons.c.o
[ 40%] Building C object CMakeFiles/opensurge.dir/src/entities/legacy/nanocalc/nanocalcext.c.o
[ 41%] Building C object CMakeFiles/opensurge.dir/src/entities/actor.c.o
[ 42%] Building C object CMakeFiles/opensurge.dir/src/entities/background.c.o
[ 43%] Building C object CMakeFiles/opensurge.dir/src/entities/brick.c.o
[ 44%] Building C object CMakeFiles/opensurge.dir/src/entities/camera.c.o
[ 45%] Building C object CMakeFiles/opensurge.dir/src/entities/character.c.o
[ 46%] Building C object CMakeFiles/opensurge.dir/src/entities/entitymanager.c.o
[ 47%] Building C object CMakeFiles/opensurge.dir/src/entities/player.c.o
[ 48%] Building C object CMakeFiles/opensurge.dir/src/entities/particle.c.o
[ 49%] Building C object CMakeFiles/opensurge.dir/src/entities/renderqueue.c.o
[ 50%] Building C object CMakeFiles/opensurge.dir/src/misc/icon.c.o
[ 51%] Building C object CMakeFiles/opensurge.dir/src/misc/credits.c.o
[ 52%] Building C object CMakeFiles/opensurge.dir/src/main.c.o
[ 53%] Linking C executable ../opensurge
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `setup_surgeengine':
scripting.c:(.text+0x4a): undefined reference to `surgescript_transform_use_inverted_y'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `scripting_resume_vm':
scripting.c:(.text+0x568): undefined reference to `surgescript_vm_resume'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `scripting_util_world_position':
scripting.c:(.text+0x631): undefined reference to `surgescript_transform_util_worldposition2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `scripting_util_is_object_inside_screen':
scripting.c:(.text+0x831): undefined reference to `surgescript_transform_util_worldposition2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `scripting_pause_vm':
scripting.c:(.text+0x51c): undefined reference to `surgescript_vm_pause'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `scripting_util_world_angle':
scripting.c:(.text+0x665): undefined reference to `surgescript_transform_util_worldangle2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `scripting_util_set_world_position':
scripting.c:(.text+0x682): undefined reference to `surgescript_transform_util_setworldposition2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/scripting.c.o: in function `scripting_util_set_world_angle':
scripting.c:(.text+0x695): undefined reference to `surgescript_transform_util_setworldangle2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/actor.c.o: in function `fun_onrender':
actor.c:(.text+0x5f2): undefined reference to `surgescript_transform_util_lossyscale2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_getangle':
transform.c:(.text+0x4d): undefined reference to `surgescript_transform_util_worldangle2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_lookat':
transform.c:(.text+0x18e): undefined reference to `surgescript_transform_util_lookat2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_getlossyscale':
transform.c:(.text+0x262): undefined reference to `surgescript_transform_util_lossyscale2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_getup':
transform.c:(.text+0x8ee): undefined reference to `surgescript_transform_util_up2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_getposition':
transform.c:(.text+0xa1b): undefined reference to `surgescript_transform_util_worldposition2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_getright':
transform.c:(.text+0xb3e): undefined reference to `surgescript_transform_util_right2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_setangle':
transform.c:(.text+0xc2a): undefined reference to `surgescript_transform_util_setworldangle2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/transform.c.o: in function `fun_setposition':
transform.c:(.text+0x10a0): undefined reference to `surgescript_transform_util_setworldposition2d'
/usr/bin/ld: CMakeFiles/opensurge.dir/src/scripting/vector2.c.o: in function `scripting_register_vector2':
vector2.c:(.text+0xd5b): undefined reference to `surgescript_transform_is_using_inverted_y'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/opensurge.dir/build.make:1624: ../opensurge] Erro 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/opensurge.dir/all] Erro 2
make: *** [Makefile:130: all] Erro 2
```

2021-11-09 00:12 UTC, alemart commented
Did you compile the latest SurgeScript from the sources provided at https://github.com/alemart/surgescript ? Simply follow the instructions provided in the README.

You will be able to compile Open Surge as soon as both libsurgescript and liballegro5 are correctly set up. Since you're on Ubuntu, another option is to use the Snap package, or alternatively Flatpak - both found at https://opensurge2d.org

2021-11-11 13:19 UTC, jorgesumle commented
> Did you compile the latest SurgeScript from the sources provided at https://github.com/alemart/surgescript ?

Yes, and I executed `sudo make install`.

> You will be able to compile Open Surge as soon as both libsurgescript and liballegro5 are correctly set up. Since you're on Ubuntu, another option is to use the Snap package, or alternatively Flatpak - both found at https://opensurge2d.org

I don't know what's wrong. 

```
14:15 $ surgescript --version
0.5.5.1
✔ ~/Repositorios/opensurge/build [master ↓·2↑·3|✔] 
14:16 $ apt show liballegro5-dev
Package: liballegro5-dev
Version: 2:5.2.6.0-1
Priority: extra
Section: universe/libdevel
Source: allegro5
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 860 kB
Depends: liballegro5.2 (= 2:5.2.6.0-1), libc-dev, libgl1-mesa-dev, libglu1-mesa-dev, libice-dev, libsm-dev, libx11-dev, libxcursor-dev, libxext-dev, libxinerama-dev, libxpm-dev, libxrandr-dev
Recommends: liballegro-acodec5-dev, liballegro-audio5-dev, liballegro-dialog5-dev, liballegro-image5-dev, liballegro-physfs5-dev, liballegro-ttf5-dev, liballegro-video5-dev
Suggests: allegro5-doc
Homepage: http://liballeg.org/
Download-Size: 98,9 kB
APT-Manual-Installed: yes
APT-Sources: http://es.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: development files for the Allegro 5 library
 This package is needed to build programs using the Allegro 5 library.
 Contains header files.
 .
 Allegro is a cross-platform library intended for use in computer games
 and other types of multimedia programming. Allegro 5 is the latest major
 revision of the library, designed to take advantage of modern hardware
 (e.g. hardware acceleration using 3D cards) and operating systems.
 Although it is not backwards compatible with earlier versions, it still
 occupies the same niche and retains a familiar style.

```

Can you test if there is any issue with how the text shows up in-game and merge if there isn't any problem?

2021-11-11 14:22 UTC, alemart commented
You may have two versions of libsurgescript installed in your system.

How did you manage to play Open Surge so far? Are you using Snap? Flatpak?

2021-11-11 15:30 UTC, Wuzzy2 commented
I don't speak Esperanto, but I can still see when strings are too long. Here are strings that overbleed:

* translation of "Show FPS" (overbleeds into "YES/NO" in options screen)
* "Poentaro" does not overbleed, but it touches the score. If the text could just be moved a few pixels to the left, it would work
* In the editor help screen: "Majuskliga klavo + Sagaj klavo" and one similar string. Needs to be shortened drastically
* The "congratulations" text is one line too long, 7 instead of 6 (consider deleting a linebreak)

2021-11-11 21:51 UTC, jorgesumle commented
I hope everything fits now.

2021-11-12 15:10 UTC, alemart requested changes
You can use the snap to test the translation:

1. Create a folder called `languages` in `$HOME/snap/opensurge/current/.local/share/opensurge2d/opensurge/`
2. Copy `esperanto.lng` to `$HOME/snap/opensurge/current/.local/share/opensurge2d/opensurge/languages/`
3. Run the game, i.e., `snap run opensurge`
4. Go to the Options screen, select Change language and pick Esperanto.

I await your full testing before merging the PR.

2021-11-12 15:15 UTC, alemart commented
In the Options screen, highlight Stage Select, press RIGHT 3 times and enter. This neat trick gives you access to all scenes:

![Captura de tela_2021-11-12_12-13-16](https://user-images.githubusercontent.com/221477/141489595-0d95b04d-66a1-49e0-8eac-a626d64cd554.png)

2021-11-12 19:51 UTC, jorgesumle commented
```
$ sudo chmod -R 777 ~/snap/opensurge/
jorge@jorge:~/snap/opensurge/62/.local/opensurge2d/opensurge/languages$ ls $HOME/snap/opensurge/62/.local/share/opensurge2d/opensurge/languages/
ls: impossível aceder a '/home/jorge/snap/opensurge/62/.local/share/opensurge2d/opensurge/languages/': Ficheiro ou pasta inexistente
jorge@jorge:~/snap/opensurge/62/.local/opensurge2d/opensurge/languages$ ls
esperanto.lng
```

It's weird. In theory, I'm inside the right directory and the file is there, but the game still doesn't detect it, gave it 777 permissions. I don't see the other files. I never edited a snap.

The `current` folder links to `62`, which is where I am.
```
jorge@jorge:~/snap/opensurge$ ls -l
total 8
drwxrwxrwx 4 jorge jorge 4096 nov 12 20:45 62
drwxrwxrwx 3 jorge jorge 4096 nov 12 20:39 common
lrwxrwxrwx 1 jorge jorge    2 oct 24 18:01 current -> 62
```

2021-11-13 13:04 UTC, alemart commented
Hi @jorgesumle . It's `.local/share/opensurge2d`, not `.local/opensurge2d`. Run this on a terminal:
```
FOLDER=~/snap/opensurge/current/.local/share/opensurge2d/opensurge/languages
mkdir -p $FOLDER
wget https://raw.githubusercontent.com/alemart/opensurge/398f365ce1fb43dd93aa01a262b8f4edae65c1ff/languages/esperanto.lng -O $FOLDER/esperanto.lng
ls -la $FOLDER
```
You should see `esperanto.lng` in `$FOLDER`:
```
$ ls -la $FOLDER
total 24
drwxrwxr-x 2 alexandre alexandre  4096 nov 13 09:57 .
drwxr-xr-x 3 alexandre alexandre  4096 nov 13 09:57 ..
-rw-rw-r-- 1 alexandre alexandre 16117 nov 13 09:57 esperanto.lng
```
Next,
```
snap run opensurge
```

2021-11-13 13:25 UTC, alemart commented
This picture is from the latest stable snap release, running version 0.5.2.1 of the engine:
![s000](https://user-images.githubusercontent.com/221477/141645218-b10991af-8cf2-4c77-af39-909e36d5ad4c.png)

2021-11-14 13:13 UTC, jorgesumle commented
Here I wanted to write the "N" near the word, but it thought it was part of the variable and later said null, so I had to add a `-` before the n. How to write it together? Also, there is I thing I can't do: it should say "SAGAJ**N** KLAVOJN" (accusative), but the variable is named SAGAJ KLAVOJ. I think you can do that kind of things with [Fluent](https://projectfluent.org/), but not easily with GNU gettext.

![Captura de ecrã de 2021-11-14 14-06-23](https://user-images.githubusercontent.com/14212780/141682311-ef4b3dbe-f866-4bc0-a5a2-501afbc1d574.png)

2021-11-14 13:45 UTC, alemart commented
I'm glad to see that you have succeeded in testing the translation.

Regarding your question, define new variables to hold the modifications. For example, in the input devices section, a new Esperanto-specific variable called `INPUT_KEYB_DIRECTIONAL__EO` could be defined as follows:
```
//
// Section: input devices
//

// keyboard
INPUT_KEYB_DIRECTIONAL      "la SAGAJ KLAVOJ"
INPUT_KEYB_DIRECTIONAL__EO  "la SAGAJN KLAVOJN"

// ...
```
Would that work?

2021-11-14 17:42 UTC, jorgesumle commented
> Would that work?

What about the function `static const char* f_input_directional() { return lang_get(input_is_joystick_enabled() ? "INPUT_JOY_DIRECTIONAL" : "INPUT_KEYB_DIRECTIONAL"); }`? I would need to change that for my constant to be detected, and modifying code for a translation doesn't look good to me.

Can't you do something like "$VARIABLE"N so that the variable is expanded without confusing the N for the variable name?

2021-11-14 22:24 UTC, alemart commented
> Can't you do something like "$VARIABLE"N so that the variable is expanded without confusing the N for the variable name?

True. I need to change the code. How about `${VARIABLE}N`? I'll get back to you.

2021-11-15 14:36 UTC, alemart commented
@jorgesumle It's now possible to use variables as in `${VARIABLE}` and `${ANOTHER_${VARIABLE}}`. This can be seen in 35dce35.

I have uploaded a snap with the new feature for the amd64 architecture. In order to update, please run:
```
snap refresh opensurge --channel=latest/edge/translation-update
```
Next, launch the game as usual:
```
snap run opensurge
```
Please let me know if you succeed or not. The title of the window should be Open Engine Surge 0.6.0:

![Captura de tela_2021-11-15_11-32-34](https://user-images.githubusercontent.com/221477/141799773-869a13b4-8f94-4639-9ce0-15c3f80fcf49.png)

2021-11-15 18:42 UTC, jorgesumle commented
> How about ${VARIABLE}N? 

That's nice!

I could install it, but I don't know how I should reference the accusative string in `LEV_DEMO_1`.

2021-11-16 00:50 UTC, alemart commented
> I could install it, but I don't know how I should reference the accusative string in LEV_DEMO_1.

Simply follow the example of the [updated English translation](https://github.com/alemart/opensurge/blob/master/languages/english.lng).

1. Update `LANG_COMPATIBILITY` to `"0.6.0"`
2. Define the accusative strings in new variables with the __EO suffix:
```
//
// Section: input devices
//

// keyboard
INPUT_KEYB_DIRECTIONAL      "la SAGAJ KLAVOJ"
INPUT_KEYB_DIRECTIONAL__EO  "la SAGAJN KLAVOJN"

// ...

// joystick
INPUT_JOY_DIRECTIONAL       "la STIRSTANGO"
INPUT_JOY_DIRECTIONAL__EO   "?????"
```
3. Define a new string `INPUT_DIRECTIONAL__EO` as in the new English file:
```
INPUT_DIRECTIONAL__EO       "${INPUT_${INPUT_TYPE}_DIRECTIONAL__EO}"
```
`${INPUT_TYPE}` will be resolved to either `JOY` or `KEYB`. Therefore, `$INPUT_DIRECTIONAL__EO` will be resolved to the appropriate string.

What do you think?

2021-11-16 11:35 UTC, jorgesumle commented
> What do you think?

A bit complicated to non-technical people, but it looks good.

2021-11-16 12:59 UTC, alemart commented
Great. Is the translation fully tested?

2021-11-16 20:07 UTC, jorgesumle commented
Yes

2021-11-17 00:08 UTC, alemart approved these changes
Great! Thank you for contributing to Open Surge! You're the Esperanto translator and your name will show up in the credits screen.

2021-11-17 00:09 UTC, merged